name = "ConsistencyResampling"
uuid = "4937dc1f-c7a3-5772-9d42-4a8277f2eb51"
authors = ["David Widmann <david.widmann@it.uu.se>"]
version = "0.2.1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.32, 0.33"
julia = "1"
